In [1]:
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
type(n1)

numpy.ndarray

In [3]:
import numpy as np
n2 = ([[10,20,30,40],[40,30,20,10]])
n2

[[10, 20, 30, 40], [40, 30, 20, 10]]

In [5]:
type(n2)

list

In [8]:
import numpy as np
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

In [9]:
import numpy as np
n4 = np.zeros((5,6))
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
import numpy as np
n5 = np.full((3,3),10)
n5

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [11]:
import numpy as np
n6 = np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
import numpy as np
n7 = np.arange(20,101,11)
n7

array([20, 31, 42, 53, 64, 75, 86, 97])

In [15]:
import numpy as np
n8 = np.random.randint(22,53,8)
n8

array([35, 26, 41, 31, 52, 37, 29, 27])

In [17]:
import numpy as np
n8 = np.array([[1,2,3],[4,5,6]])


In [18]:
n8

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
n8.shape

(2, 3)

In [20]:
n8.shape = (3,2)

In [21]:
n8

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
import numpy as np
n9 = np.array([10,20,30])
n10 = np.array([40,50,60])

In [25]:
np.vstack((n9,n10))

array([[10, 20, 30],
       [40, 50, 60]])

In [26]:
np.hstack((n9,n10))

array([10, 20, 30, 40, 50, 60])

In [28]:
np.column_stack((n9,n10))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [29]:
n11=np.array([1,2,3])
n12=np.array([4,5,6])
n13=np.array([7,8,9])

In [30]:
np.vstack((n11,n13,n12))

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [10]:
import numpy as np
n14=np.array([10,20,30,40])
n15=np.array([30,40,50])
n16=np.array([40,50,60])

In [11]:
np.intersect1d(n14,n15)

array([30, 40])

In [16]:
np.intersect1d(n15,n16)

array([40, 50])

In [17]:
np.setdiff1d(n14,n15)

array([10, 20])

In [19]:
np.setdiff1d(n16,n15)

array([60])

In [20]:
np.setdiff1d(n14,n15,n16)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [21]:
n17=np.array([10,20])
n18=np.array([30,40])

In [24]:
np.sum([n17,n18])

100

In [25]:
np.sum([n17,n18],axis=0)

array([40, 60])

In [26]:
np.sum([n17,n18],axis=1)

array([30, 70])

In [28]:
n19=np.array([40,50,60])
n19=n19+1
n19

array([41, 51, 61])

In [29]:
n20=np.array([40,50,60])
n20=n20-1
n20

array([39, 49, 59])

In [30]:
n21=np.array([40,50,60])
n21=n21*3
n21

array([120, 150, 180])

In [31]:
n22=np.array([40,50,60])
n22=n22/7
n22

array([5.71428571, 7.14285714, 8.57142857])

In [32]:
n23=np.array([10,20,30,40,50,60])
n24=np.array([30,40,33])
np.mean(n23)

35.0

In [33]:
np.mean(n24)

34.333333333333336

In [34]:
np.std(n23)

17.07825127659933

In [35]:
np.median(n23)

35.0

In [41]:
n35=np.array([10,20,30,40,50,60])
np.save('my_numpy',n35)

In [42]:
n36=np.load('my_numpy.npy')
n36

array([10, 20, 30, 40, 50, 60])

In [44]:
import nump as np
arr=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
print('2nd element on 1st dim: ',arr[0,1])

SyntaxError: invalid syntax (<ipython-input-44-2e08d8065aa4>, line 2)

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[5 6]


In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [56]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1,1:4])

[7 8 9]


In [57]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [58]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [59]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [62]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [63]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
